language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update || true
  - composer install

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

dist: trusty
